<?php
namespace Diva\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository {

    public function getAll(){
        // example1: creating a QueryBuilder instance
        $qb = $this->em->createQueryBuilder();
        $qb
        ->select('p.id')
        ->addSelect('p.name')
        ->from('Diva:Product', 'p')
        ;

        // $qb instanceof QueryBuilder
        $query = $qb->getQuery();
        return $query->getResult();

    }

    public function getProductFeatures(int $pId){
        // example1: creating a QueryBuilder instance
        $qb = $this->em->createQueryBuilder();
        /*
        $qb->select('u')
        ->from('Diva:User', 'u')
        ->where('u.id = :identifier')
        ->orderBy('u.name', 'ASC')
        ->setParameter('identifier', 1);
        */

        $qb
        ->select('p.id')
        ->addSelect('p.name')
        ->addSelect('f.name as f_name')
        ->from('Diva:Product', 'p')
        ->leftJoin('p.features', 'f')
        ->where('p.id = :pId')
        ->setParameter('pId', $pId)
        ;

        // $qb instanceof QueryBuilder
        $query = $qb->getQuery();
        return $query->getResult();

    }

}