<?php
namespace Diva\Repository;

use Diva\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function getByEmail(string $email): User {

        $qb = $this->em->createQueryBuilder();
        $qb->select('u')
        ->from('Diva:User', 'u')
        ->where('u.email = :uEmail')
        ->setParameter('uEmail', $email);

        $query = $qb->getQuery();
        return $query->getResult();      
        
    }

}